export const musicList = {
  doodle: {
    src: "/music/doodle.webm",
    artist: "Zachz Winner",
    title: "doodle",
    link: "https://youtu.be/-iM7KCEt5zs?si=HrqlfZiWwmGMJI7n",
    bpm: 160,
    startOffset: 0,
    firstBeatOffset: 0.5,
    lowFreqStart: 0,
    lowFreqEnd: 64,
    duration: 74,
  },
  discoupled: {
    src: "/music/discopled.webm",
    artist: "Zachz Winner",
    title: "discopled",
    link: "https://youtu.be/UWpUCmXokgM?si=dIlTlGougOkcY3bT",
    bpm: 152,
    startOffset: 0,
    firstBeatOffset: 0,
    lowFreqStart: 0,
    lowFreqEnd: 64,
    duration: 86,
  },
  "bad-apple-ft-sekai-off-vocal": {
    src: "/music/bad-apple-ft-sekai-off-vocal.webm",
    bpm: 138,
    artist: "25-ji, Nightcord de",
    title: "(off vocal) Bad Apple!! feat.SEKAI",
    link: "https://youtu.be/h87WUOEPUCg?si=jTRAN3sUJ1XVZQBh",
    startOffset: 0,
    firstBeatOffset: 1,
    lowFreqStart: 0,
    lowFreqEnd: 64,
    duration: 229,
  },
  "bad-apple-ft-sekai": {
    src: "/music/bad-apple-ft-sekai.webm",
    bpm: 138,
    artist: "25-ji, Nightcord de",
    title: "Bad Apple!! feat.SEKAI",
    link: "https://youtu.be/v-fc1zv31zE?si=9NauF-kKzT6IqQsx",
    startOffset: 1,
    firstBeatOffset: 1,
    lowFreqStart: 16,
    lowFreqEnd: 18,
    duration: 231,
  },
};

export const badAppleLyrics: {
  text: string;
  startTime: number;
  endTime?: number;
}[] = [
  { text: "流れてく 時の中ででも", startTime: 29 },
  { text: "気だるさが ほらグルグル廻って", startTime: 33.013 },
  { text: "私から 離れる心も", startTime: 36.415 },
  { text: "見えないわ そう知らない?", startTime: 39.952 },
  { text: "自分から 動くこともなく", startTime: 43.172 },
  { text: "時の隙間に 流され続けて", startTime: 46.891 },
  { text: "知らないわ 周りのことなど", startTime: 50.337 },
  { text: "私は私 それだけ", startTime: 53.83 },

  { text: "夢見てる? 何も見てない?", startTime: 57.095 },
  { text: "語るも無駄な 自分の言葉?", startTime: 60.133 },
  { text: "悲しむなんて 疲れるだけよ", startTime: 63.58 },
  { text: "何も感じず 過ごせばいいの", startTime: 67.118 },
  { text: "戸惑う言葉 与えられても", startTime: 70.61 },
  { text: "自分の心 ただ上の空", startTime: 74.056 },
  { text: "もし私から 動くのならば", startTime: 77.548 },
  { text: "全変えるのなら 黒にする", startTime: 81.04 },

  { text: "こんな自分に 未来はあるの?", startTime: 84.532 },
  { text: "こんな世界に 私はいるの?", startTime: 88.025 },
  { text: "今切ないの? 今悲しいの?", startTime: 91.471 },
  { text: "自分のことも わからないまま", startTime: 94.963 },
  { text: "歩むことさえ 疲れるだけよ", startTime: 98.41 },
  { text: "人のことなど 知りもしないわ", startTime: 101.902 },
  { text: "こんな私も 変われるのなら", startTime: 105.44 },
  { text: "もし変われるの なら白になる", startTime: 108.886, endTime: 112.378 },

  { text: "流れてく 時の中ででも", startTime: 126.891 },
  { text: "気だるさが ほらグルグル廻って", startTime: 130.428 },
  { text: "私から 離れる心も", startTime: 133.83 },
  { text: "見えないわ そう知らない?", startTime: 137.367 },
  { text: "自分から 動くこともなく", startTime: 140.632 },
  { text: "時の隙間に 流され続けて", startTime: 144.26 },
  { text: "知らないわ 周りのことなど", startTime: 147.7 },
  { text: "私は私 それだけ", startTime: 151.244 },

  { text: "夢見てる? 何も見てない?", startTime: 154.555 },
  { text: "語るも無駄な 自分の言葉?", startTime: 157.594 },
  { text: "悲しむなんて 疲れるだけよ", startTime: 161.04 },
  { text: "何も感じず 過ごせばいいの", startTime: 164.487 },
  { text: "戸惑う言葉 与えられても", startTime: 167.979 },
  { text: "自分の心 ただ上の空", startTime: 171.426 },
  { text: "もし私から 動くのならば", startTime: 174.918 },
  { text: "すべて変えるのなら 黒にする", startTime: 178.455 },

  { text: "動くのならば 動くのならば", startTime: 181.947 },
  { text: "全て壊すわ 全て壊すわ", startTime: 185.44 },
  { text: "悲しむならば 悲しむならば", startTime: 188.932 },
  { text: "私の心 白く束ねる", startTime: 192.333 },

  { text: "貴方の事も 私の事も", startTime: 195.825 },
  { text: "全ての事も まだ知らないの", startTime: 199.317 },
  { text: "重い目蓋を 開けたのならば", startTime: 202.809 },
  { text: "全壊すのなら 黒になれ", startTime: 206.256, endTime: 210.256 },
];
